# Generated by Django 3.2 on 2021-05-21 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField()),
                ('TotalPrice', models.FloatField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(default='', upload_to='')),
                ('ItemPrice', models.FloatField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('details_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_bought_quant', models.IntegerField()),
                ('item_price', models.FloatField(default=0)),
                ('item_det_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.item')),
                ('order_det_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.customerorder')),
            ],
            options={
                'unique_together': {('order_det_id', 'item_det_id')},
            },
        ),
        migrations.AddField(
            model_name='customerorder',
            name='items',
            field=models.ManyToManyField(through='coffeeapp.OrderDetail', to='coffeeapp.Item'),
        ),
    ]
